"""Reviews table 'is_active' default changed

Revision ID: 57c55f2785c3
Revises: 74b2e8729cb2
Create Date: 2025-08-21 23:16:42.910869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c55f2785c3'
down_revision: Union[str, None] = '74b2e8729cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
